### ISSUE TITLE
Fix Travis CI of this repo

### ISSUE THREAD

**Issue by sidhyatikku** [sidhyatikku/rick#6]
Travis cannot build this project. Go fix those errors!

Hint: Fibo .cpp works on TurboC++

**Comment by willany** [comment]
Could you try to fix this?

<img width="431" alt="captura de tela 2018-10-29 as 10 15 07" src="https://user-images.githubusercontent.com/629029/47652043-a158d980-db63-11e8-93f4-5a344243f8a0.png">

**Comment by sidhyatikku** [comment]
Would you like me to assign you this task?

**Comment by dhruvhacks** [comment]
May I take up this issue?? @sidhyatikku
